name: ngobatyuk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^15.0.0
  timezone: ^0.9.0
  permission_handler: ^10.0.0
  path_provider: ^2.0.15
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
